/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package register.app.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RegisterUser service. Represents a row in the &quot;RegisterApp_RegisterUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>register.app.backend.model.impl.RegisterUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>register.app.backend.model.impl.RegisterUserImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegisterUser
 * @generated
 */
@ProviderType
public interface RegisterUserModel
	extends BaseModel<RegisterUser>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a register user model instance should use the {@link RegisterUser} interface instead.
	 */

	/**
	 * Returns the primary key of this register user.
	 *
	 * @return the primary key of this register user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this register user.
	 *
	 * @param primaryKey the primary key of this register user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this register user.
	 *
	 * @return the uuid of this register user
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this register user.
	 *
	 * @param uuid the uuid of this register user
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the register user ID of this register user.
	 *
	 * @return the register user ID of this register user
	 */
	public long getRegisterUserId();

	/**
	 * Sets the register user ID of this register user.
	 *
	 * @param registerUserId the register user ID of this register user
	 */
	public void setRegisterUserId(long registerUserId);

	/**
	 * Returns the register user uuid of this register user.
	 *
	 * @return the register user uuid of this register user
	 */
	public String getRegisterUserUuid();

	/**
	 * Sets the register user uuid of this register user.
	 *
	 * @param registerUserUuid the register user uuid of this register user
	 */
	public void setRegisterUserUuid(String registerUserUuid);

	/**
	 * Returns the group ID of this register user.
	 *
	 * @return the group ID of this register user
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this register user.
	 *
	 * @param groupId the group ID of this register user
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this register user.
	 *
	 * @return the company ID of this register user
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this register user.
	 *
	 * @param companyId the company ID of this register user
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this register user.
	 *
	 * @return the user ID of this register user
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this register user.
	 *
	 * @param userId the user ID of this register user
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this register user.
	 *
	 * @return the user uuid of this register user
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this register user.
	 *
	 * @param userUuid the user uuid of this register user
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this register user.
	 *
	 * @return the user name of this register user
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this register user.
	 *
	 * @param userName the user name of this register user
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this register user.
	 *
	 * @return the create date of this register user
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this register user.
	 *
	 * @param createDate the create date of this register user
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this register user.
	 *
	 * @return the modified date of this register user
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this register user.
	 *
	 * @param modifiedDate the modified date of this register user
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this register user.
	 *
	 * @return the name of this register user
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this register user.
	 *
	 * @param name the name of this register user
	 */
	public void setName(String name);

	/**
	 * Returns the surname of this register user.
	 *
	 * @return the surname of this register user
	 */
	@AutoEscape
	public String getSurname();

	/**
	 * Sets the surname of this register user.
	 *
	 * @param surname the surname of this register user
	 */
	public void setSurname(String surname);

	/**
	 * Returns the lastname of this register user.
	 *
	 * @return the lastname of this register user
	 */
	@AutoEscape
	public String getLastname();

	/**
	 * Sets the lastname of this register user.
	 *
	 * @param lastname the lastname of this register user
	 */
	public void setLastname(String lastname);

	/**
	 * Returns the national ID of this register user.
	 *
	 * @return the national ID of this register user
	 */
	@AutoEscape
	public String getNationalId();

	/**
	 * Sets the national ID of this register user.
	 *
	 * @param nationalId the national ID of this register user
	 */
	public void setNationalId(String nationalId);

	/**
	 * Returns the email of this register user.
	 *
	 * @return the email of this register user
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this register user.
	 *
	 * @param email the email of this register user
	 */
	public void setEmail(String email);

	/**
	 * Returns the question type of this register user.
	 *
	 * @return the question type of this register user
	 */
	@AutoEscape
	public String getQuestionType();

	/**
	 * Sets the question type of this register user.
	 *
	 * @param questionType the question type of this register user
	 */
	public void setQuestionType(String questionType);

	/**
	 * Returns the description of this register user.
	 *
	 * @return the description of this register user
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this register user.
	 *
	 * @param description the description of this register user
	 */
	public void setDescription(String description);

}